version: "3.8"

services:
  pg-stories-service:
    image: postgres:14-alpine3.17
    container_name: pg-stories-service
    restart: always
    environment:
      - POSTGRES_HOST=5432
      - POSTGRES_DB=stories-db
      - POSTGRES_USER=stories-db-user
      - POSTGRES_PASSWORD=stories-db-password
    ports:
      - "54365:5432"
    volumes:
      - ./stories_service_postgresql:/var/lib/postgresql/data

  stories_service-migrator-pg:
    container_name: stories_service-migrator-pg
    platform: linux/amd64
    build:
      context: ./stories_service
      dockerfile: migration_prod.Dockerfile
    restart: on-failure
    environment:
      DB_HOST: pg-stories-service
    depends_on:
      - pg-stories-service