version: "3.8"

services:
  api_gateway:
    platform: linux/amd64
    image: cr.selcloud.ru/yanbackend/api_gateway:latest
    container_name: api_gateway
    restart: always
    ports:
      - '8080:8080'

  pg-stories-service:
    image: postgres:14-alpine3.17
    container_name: pg-stories-service
    restart: always
    environment:
      - POSTGRES_HOST=5432
      - POSTGRES_DB=stories-db
      - POSTGRES_USER=stories-db-user
      - POSTGRES_PASSWORD=stories-db-password
    ports:
      - "54365:5432"
    volumes:
      - ./stories_service_postgresql:/var/lib/postgresql/data

  stories_service:
    container_name: stories_service
    platform: linux/amd64
    image: cr.selcloud.ru/yanbackend/stories_service:latest
    restart: always
    environment:
      - config_path=prod.env
    ports:
      - "30016:30016"
    depends_on:
      - pg-stories-service

  stories_service-migrator-pg:
    container_name: stories_service-migrator-pg
    platform: linux/amd64
    image: cr.selcloud.ru/yanbackend/stories_service_migrator_pg:latest
    restart: on-failure
    environment:
      DB_HOST: pg-stories-service
    depends_on:
      - pg-stories-service