version: "3.8"

services:
  api_gateway:
    platform: linux/amd64
    image: cr.selcloud.ru/yanbackend/api_gateway:latest
    container_name: api_gateway
    restart: always
    ports:
      - '50053:50053'
    networks: [ "yancobackend" ]

networks:
  yancobackend:
    name: yancobackend