name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  REGISTRY: "cr.selcloud.ru/yanbackend"
  IMAGE_NAME_API_GATEWAY: "api_gateway"
  IMAGE_NAME_BANNERS_SERVICE: "banners_service"
  IMAGE_NAME_GIS_SERVICE: "gis_service"
  IMAGE_NAME_STORIES_SERVICE: "stories_service"
  IMAGE_NAME_STORIES_SERVICE_MIGRATOR: "stories_service_migrator_pg"
  CONTAINER_NAME: "yancobackend"

jobs:
  image-build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Registry
        run: docker login -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }} $REGISTRY

      - name: Build and Push Api-gateway Docker Image
        run: |
          TAG_NAME=$(echo $GITHUB_SHA | head -c7)
          docker buildx create --use
          docker buildx build --no-cache --push -t $REGISTRY/$IMAGE_NAME_API_GATEWAY:latest -t $REGISTRY/$IMAGE_NAME_API_GATEWAY:$TAG_NAME -f api_gateway/Dockerfile api_gateway/ 

      - name: Build and Push Banners-service Docker Image
        run: |
          TAG_NAME=$(echo $GITHUB_SHA | head -c7)
          docker buildx create --use
          docker buildx build --no-cache --push -t $REGISTRY/$IMAGE_NAME_BANNERS_SERVICE:latest -t $REGISTRY/$IMAGE_NAME_BANNERS_SERVICE:$TAG_NAME -f banners_service/Dockerfile banners_service/ 

      - name: Build and Push GIS-service Docker Image
        run: |
          TAG_NAME=$(echo $GITHUB_SHA | head -c7)
          docker buildx create --use
          docker buildx build --no-cache --push -t $REGISTRY/$IMAGE_NAME_GIS_SERVICE:latest -t $REGISTRY/$IMAGE_NAME_GIS_SERVICE:$TAG_NAME -f gis_service/Dockerfile gis_service/ 

      - name: Build and Push Stories-service Docker Image
        run: |
          TAG_NAME=$(echo $GITHUB_SHA | head -c7)
          docker buildx create --use
          docker buildx build --no-cache --push -t $REGISTRY/$IMAGE_NAME_STORIES_SERVICE:latest -t $REGISTRY/$IMAGE_NAME_STORIES_SERVICE:$TAG_NAME -f stories_service/Dockerfile stories_service/ 
          docker buildx build --no-cache --push -t $REGISTRY/$IMAGE_NAME_STORIES_SERVICE_MIGRATOR:latest -t $REGISTRY/$IMAGE_NAME_STORIES_SERVICE_MIGRATOR:$TAG_NAME -f stories_service/migration_prod.Dockerfile stories_service/ 

  deploy-image:
    runs-on: ubuntu-latest
    needs: image-build-and-push

    steps:
      - name: Checkout master
        uses: actions/checkout@v3

      - name: Copy docker-compose file via ssh key
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSHKEY }}
          rm: true
          source: docker-compose.yml
          target: /root/yancobackend/

      - name: Deploy to Selectel Cloud via SSH action
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSHKEY }}
          envs: IMAGE_NAME,REGISTRY,GITHUB_SHA,CONTAINER_NAME
          script: |
            # Set up variables
            TAG_NAME=$(echo $GITHUB_SHA | head -c7)
            
            # Login into Selectel Registry
            docker login -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }} $REGISTRY
            
            # Stop all containers and delete
            docker stop $(docker ps -a -q)
            docker rm $(docker ps -a -q)
            
            # Remove all old images
            docker rmi $(docker images -a -q)
            
            # Run a new container from a new image
            docker-compose --project-name $CONTAINER_NAME -f /root/yancobackend/docker-compose.yml up -d --build